version: "2"
services:
    deluge:
        image: linuxserver/deluge
        restart: always
        ports:
                - "8112:8112"
                - "58846:58846"
                - "58946:58946"
                - "58946:58946/udp"
        volumes:
                - /share/appdata/deluge:/config
                - /share/downloads:/downloads
        environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}

    sonarr:
        image: linuxserver/sonarr
        restart: always
        depends_on:
                - bit
                - jackett
        ports:
                - "8989:8989"
        volumes:
                - /share/appdata/sonarr:/config
                - /share/downloads:/downloads
                - /share/series/series:/series
                - /share/series/kids:/serieskids
        environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}

    radarr:
        image: linuxserver/radarr
        restart: always
        depends_on:
                - bit
                - jackett
        ports:
                - "7878:7878"
        volumes:
                - /share/appdata/radarr:/config
                - /share/downloads:/downloads
                - /share/movies/movies:/movies
                - /share/movies/kids:/movieskids
        environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}

    jackett:
        image: linuxserver/jackett
        restart: always
        ports:
                - "9117:9117"
        volumes:
                - /share/appdata/jackett:/config
        environment:
                - PUID=${PUID}
                - PGID=${PGID}
                - TZ=${TZ}

